name: All Tests ( openjdk8 )

on: [push]

jobs:
  Ubuntu:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: joschi/setup-jdk@v2
        with:
          distribution: 'adopt'
          java-version: 11
      - name: Set JAVA_TOOL_OPTIONS
        run: |
          NEW_JAVA_TOOL_OPTIONS="${{ env.JAVA_TOOL_OPTIONS }} -Djdk.util.zip.disableZip64ExtraFieldValidation=true -Djdk.nio.zipfs.allowDotZipEntry=true --add-opens=java.base/java.net=ALL-UNNAMED"
          echo "JAVA_TOOL_OPTIONS=$NEW_JAVA_TOOL_OPTIONS" >> $GITHUB_ENV
      - name: Build with Maven
        run: |
          mvn -B clean install --file pom.xml -fae
        env:
          JAVA_TOOL_OPTIONS: ${{ env.JAVA_TOOL_OPTIONS }}
          CI_BUILD_SKIP: true

#  MacOS:
#
#    runs-on: macOS-latest
#
#    steps:
#      - uses: actions/checkout@v2
#      - name: Set up JDK 11
#        uses: joschi/setup-jdk@v2
#        with:
#          distribution: 'adopt'
#          java-version: 11
#      - name: Set JAVA_TOOL_OPTIONS
#        run: |
#          NEW_JAVA_TOOL_OPTIONS="${{ env.JAVA_TOOL_OPTIONS }} -Djdk.util.zip.disableZip64ExtraFieldValidation=true -Djdk.nio.zipfs.allowDotZipEntry=true --add-opens=java.base/java.net=ALL-UNNAMED"
#          echo "JAVA_TOOL_OPTIONS=$NEW_JAVA_TOOL_OPTIONS" >> $GITHUB_ENV
#      - name: Build with Maven
#        run: |
#          mvn -B clean install --file pom.xml -fae
#        env:
#          JAVA_TOOL_OPTIONS: ${{ env.JAVA_TOOL_OPTIONS }}
#

#  windows:
#
#    runs-on: windows-latest
#
#    steps:
#      - name: Support longpaths
#        run: git config --system core.longpaths true
#      - uses: actions/checkout@v2
#      - name: Set up JDK 11
#        uses: joschi/setup-jdk@v2
#        with:
#          distribution: 'adopt'
#          java-version: 11
#      - name: Set JAVA_TOOL_OPTIONS
#        run: |
#          $NEW_JAVA_TOOL_OPTIONS="${{ env.JAVA_TOOL_OPTIONS }} -Djdk.util.zip.disableZip64ExtraFieldValidation=true -Djdk.nio.zipfs.allowDotZipEntry=true --add-opens=java.base/java.net=ALL-UNNAMED"
#          echo "JAVA_TOOL_OPTIONS=$NEW_JAVA_TOOL_OPTIONS" >> $env:GITHUB_ENV
#      - name: Build with Maven
#        run: mvn -B clean install --file pom.xml -fae
#        env:
#          JAVA_TOOL_OPTIONS: ${{ env.JAVA_TOOL_OPTIONS }}
