name: Cluster tests (JDK17 & MySQL)

on: [push, pull_request]

jobs:
  ubuntu:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up MySQL
        run: |
            sudo /etc/init.d/mysql start
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          distribution: 'temurin'
          java-version: '11.0.12+7'
      - name: Build in JDK 11
        run: mvn -B clean install -DskipTests --file pom.xml
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '17.0.6'
      - name: Cluster Tests with JDK 17
        run: mvn -B clean install --file integration/pom.xml -P cluster-tests
      - name: Set up JDK 21
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '21.0.4'
      - name: Cluster Tests with JDK 21
        run: mvn -B clean install --file integration/pom.xml -P cluster-tests
